#!/usr/bin/env node
/*
 * Builds preview/index.html from src/Index.html by inlining the same
 * <?!= include('X'); ?> files Apps Script uses, plus preview/stub.js.
 *
 *   node scripts/build-preview.js           write preview/index.html
 *   node scripts/build-preview.js --check   exit 1 if preview/index.html is out of date
 */
'use strict';

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const srcDir = path.join(root, 'src');
const outFile = path.join(root, 'preview', 'index.html');
const stubFile = path.join(root, 'preview', 'stub.js');

function build() {
  let html = fs.readFileSync(path.join(srcDir, 'Index.html'), 'utf8');

  html = html.replace(/<\?!=\s*include\(\s*['"]([\w-]+)['"]\s*\);?\s*\?>/g, (_, name) => {
    const file = path.join(srcDir, name + '.html');
    if (!fs.existsSync(file)) throw new Error('include() target not found: ' + file);
    return fs.readFileSync(file, 'utf8').trim();
  });

  const leftover = html.match(/<\?[\s\S]*?\?>/);
  if (leftover) throw new Error('Unresolved Apps Script scriptlet in Index.html: ' + leftover[0]);

  const stub = fs.readFileSync(stubFile, 'utf8').trim();
  const headInsert =
    '  <meta name="viewport" content="width=device-width, initial-scale=1">\n' +
    '  <script>\n' + stub + '\n  </script>\n';
  if (!html.includes('</head>')) throw new Error('Index.html has no </head>');
  html = html.replace('</head>', headInsert + '</head>');

  const banner =
    '<!-- GENERATED by scripts/build-preview.js from src/*.html + preview/stub.js. Do not edit by hand.\n' +
    '     Uses synthetic sample data only. -->\n';
  return html.replace(/^(<!DOCTYPE html>\n?)/i, '$1' + banner);
}

const output = build();

if (process.argv.includes('--check')) {
  const current = fs.existsSync(outFile) ? fs.readFileSync(outFile, 'utf8') : '';
  if (current !== output) {
    console.error('preview/index.html is out of date. Run: node scripts/build-preview.js');
    process.exit(1);
  }
  console.log('preview/index.html is up to date.');
} else {
  fs.writeFileSync(outFile, output);
  console.log('Wrote ' + path.relative(root, outFile) + ' (' + output.length + ' bytes)');
}
